# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build

build-image:
  stage: build
  tags:
    - builder
  before_script:
    - echo "target container registry host:$CI_REGISTRY"
    - echo "glpat-aQET5A_PwPpFRQSEnKf5" | sudo docker login -u "container_registry" --password-stdin "$CI_REGISTRY"
  script:
    - git checkout "$CI_COMMIT_REF_NAME" && git pull
    - VERSION=`bash ./utility_get_git_latest_tag_name.sh`
    - sudo docker build --pull -t "$CI_REGISTRY_IMAGE:$VERSION" -f Dockerfile .
    - sudo docker images "$CI_REGISTRY_IMAGE:$VERSION" 
    - sudo docker push "$CI_REGISTRY_IMAGE:$VERSION"
  except:
    - dev
  only:
    refs:
    - master
    - main
    # variables:
    #   - $CI_COMMIT_MESSAGE =~ /demo/
  when: manual

